site_name: GPUInfoNV Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - API Reference: api_reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
